pluginManagement {
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "hide-minimega-leaderboards"

gradle.ext.defaultMc = settings.providers
    .gradleProperty("defaultMc")
    .getOrElse("1.21.10")
